#!/usr/bin/env php
<?php

include "vendor/autoload.php";

$birthDate = "1978-09-22";

$myDays = new Volosatov\PHPDays\MyDays($birthDate);

$totalDays = $myDays->getTotalDays();

echo "$birthDate : $totalDays\n";

