#!/usr/bin/env php
<?php

include "src/class.MyDays.php";
$birthDate = "1978-09-22";

$myDays = new Volosatov\Demo\MyDays($birthDate);

$totalDays = $myDays->getTotalDays();

echo "$birthDate : $totalDays\n";

